<nav class="navbar navbar-dark bg-primary">
<table align="center" width="100%">
<tr align="center">
	<td>
		<a href="index.php?c=admin&a=grid" style="text-decoration:none; color: white; color: white;">Admin</a>
	</td>
	<td>
		<a href="index.php?c=product&a=grid" style="text-decoration:none; color: white;">Product</a>
	</td>
	<td>
		<a href="index.php?c=category&a=grid" style="text-decoration:none; color: white;">Category</a>
	</td>
	<td>
		<a href="index.php?c=customer&a=grid" style="text-decoration:none; color: white;">Customer</a>
	</td>
	<td>
		<a href="index.php?c=vendor&a=grid" style="text-decoration:none; color: white;">Vendor</a>
	</td>
	<td>
		<a href="index.php?c=salesman&a=grid" style="text-decoration:none; color: white;">Salesman</a>
	</td>
	<td>
		<a href="index.php?c=shipping&a=grid" style="text-decoration:none; color: white;">Shipping</a>
	</td>
	<td>
		<a href="index.php?c=payment&a=grid" style="text-decoration:none; color: white;">Payment</a>
	</td>
	<td>
		<a href="index.php?c=attribute&a=grid" style="text-decoration:none; color: white;">Eav Attribute</a>
	</td>
</tr>
</table>
</nav>