<table align="center" width="100%" style="background: lightcyan; padding: 30px;">
<tr align="center">
	<td>
		<a href="index.php?c=admin&a=grid" style="text-decoration:none;">Admin</a>
	</td>
	<td>
		<a href="index.php?c=product&a=grid" style="text-decoration:none;">Product</a>
	</td>
	<td>
		<a href="index.php?c=category&a=grid" style="text-decoration:none;">Category</a>
	</td>
	<td>
		<a href="index.php?c=customer&a=grid" style="text-decoration:none;">Customer</a>
	</td>
	<td>
		<a href="index.php?c=vendor&a=grid" style="text-decoration:none;">Vendor</a>
	</td>
	<td>
		<a href="index.php?c=salesman&a=grid" style="text-decoration:none;">Salesman</a>
	</td>
	<td>
		<a href="index.php?c=shipping&a=grid" style="text-decoration:none;">Shipping</a>
	</td>
	<td>
		<a href="index.php?c=payment&a=grid" style="text-decoration:none;">Payment</a>
	</td>
	<td>
		<a href="index.php?c=attribute&a=grid" style="text-decoration:none;">Attribute</a>
	</td>
</tr>
</table>
