<?php $shipping = $this->getShipping()['shipping']; ?>
<!DOCTYPE html>
<html>
<head>
	<title>shipping</title>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
<form action="<?php echo $this->getUrl('save'); ?>" method="post">
	<br/>
	<table class="add-header">
		<tr align="center">
			<td><h2>SHIPPING METHOD INFORMATION</h2></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="add-data-table" align="center">
		<tr>
			<td>Name</td>
			<td><input type="text" name="shipping[name]" value="<?php echo $shipping->name; ?>"></td>
		</tr>
		<tr>
			<td>Amount</td>
			<td><input type="text" name="shipping[amount]" value="<?php echo $shipping->amount; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="shipping[status]">
					<?php foreach ($shipping->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $shipping->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2"><button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
			<button type="submit">Submit</button></td>
		</tr>
	</table>
</form>
</body>
</html>