<?php
$shippings = $this->getShippings();
?>

	<table class="manage-table" border="1px">
		<tr align="center">
			<td width="70%">MANAGE SHIPPING</td>
			<td><button class="btn btn-primary" type="submit"><a class="btn btn-primary" href="<?php echo $this->getUrl('add') ?>">ADD SHIPPING</a></button></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="table table-success table-striped">
		<?php if (!$shippings): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr align="center">
			<th>Shipping Method Id</th>
			<th>Name</th>
			<th>Amount</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($shippings as $shipping) : ?>
		<tr align="center">
			<td><?php echo $shipping->shipping_method_id; ?></td>
			<td><?php echo $shipping->name; ?></td>
			<td><?php echo $shipping->amount; ?></td>
			<td><?php echo $shipping->getStatusText(); ?></td>
			<td><?php echo $shipping->created_at; ?></td>
			<td><?php echo $shipping->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $shipping->shipping_method_id], true);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null , ['id'=> $shipping->shipping_method_id], true);?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>