<?php
$admins = $this->getAdmins();
?>

	<table class="manage-table" border="1px">
		<tr align="center">
			<td width="70%">MANAGE ADMIN</td>
			<td><button class="btn btn-primary" type="submit"><a class="btn btn-primary" href="<?php echo $this->getUrl('add') ?>">ADD ADMIN</a></button></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="table table-success table-striped">
		
		<tr align="center">
			<th>Admin Id</th>
			<th>Name</th>
			<th>email</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($admins as $admin) : ?>
		<tr align="center">
			<td><?php echo $admin->admin_id; ?></td>
			<td><?php echo $admin->name; ?></td>
			<td><?php echo $admin->email; ?></td>
			<td><?php echo $admin->getStatusText(); ?></td>
			<td><?php echo $admin->created_at; ?></td>
			<td><?php echo $admin->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $admin->admin_id], true) ?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $admin->admin_id], true) ?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>