<!DOCTYPE html>
<html>

<?php
	$this->createBlock("Html_Head")->render();
?>
<body>
	<table width="100%" border="1px solid bLack">
		<tr height="100" align="center">
			<td colspan="3">
				<?php $this->getChild('header')->render();?>
			</td>
		</tr>
		<tr height="40" align="center">
			<td colspan="3">
				<?php $this->getChild('message')->render();?>
			</td>
		</tr>
		<tr align="center">
			<td><?php $this->getChild('content')->render();  ?></td>
		</tr>
		<tr height="50" align="center">
			<td colspan="3">Footer</td>
		</tr>
	</table>
</body>
</html>