<?php
$customers = $this->getCollection();
?>

	<br/>
	<br/>
	<table class="manage-table" border="1px">
		<tr align="center">
			<td width="70%">MANAGE CUSTOMER</td>
			<td><button><a href="<?php echo $this->getUrl()->getUrl('customer','add'); ?>">ADD CUSTOMER</a></button></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="grid-table" border="1px">
		<?php if (!$customers): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr align="center">
			<th>Customer Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Gender</th>
			<th>Mobile</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
			<th>ADDRESS</th>
		</tr>
		<?php foreach ($customers->getData() as $customer) : ?>
		<tr align="center">
			<td><?php echo $customer->customer_id; ?></td>
			<td><?php echo $customer->first_name; ?></td>
			<td><?php echo $customer->last_name; ?></td>
			<td><?php echo $customer->email; ?></td>
			<td><?php echo $customer->gender; ?></td>
			<td><?php echo $customer->mobile; ?></td>
			<td><?php echo $customer->created_at; ?></td>
			<td><?php echo $customer->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl()->getUrl('customer','edit',['customer_id'=>$row->customer_id]);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl()->getUrl('customer','delete',['customer_id'=>$row->customer_id]);?>">DELETE</a></td>
			<td><a href="<?php echo $this->getUrl()->getUrl('customer_Address','grid',['customer_id'=>$row->customer_id]);?>">VIEW ADDRESS</a>
			</td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>