<?php
$customers = $this->getCustomers();
?>

	<table class="manage-table" border="1px">
		<tr align="center">
			<td width="70%">MANAGE CUSTOMER</td>
			<td><button class="btn btn-primary" type="submit"><a class="btn btn-primary" href="<?php echo $this->getUrl('add') ?>">ADD CUSTOMER</a></button></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="table table-success table-striped">
		
		<tr align="center">
			<th>Customer Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Gender</th>
			<th>Mobile</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
			<th>ADDRESS</th>
		</tr>
		<?php foreach ($customers as $customer) : ?>
		<tr align="center">
			<td><?php echo $customer->customer_id; ?></td>
			<td><?php echo $customer->first_name; ?></td>
			<td><?php echo $customer->last_name; ?></td>
			<td><?php echo $customer->email; ?></td>
			<td><?php echo $customer->gender; ?></td>
			<td><?php echo $customer->mobile; ?></td>
			<td><?php echo $customer->created_at; ?></td>
			<td><?php echo $customer->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $customer->customer_id], true);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null , ['id'=> $customer->customer_id], true);?>">DELETE</a></td>
			<td><a href="<?php echo $this->getUrl('customer_Address',null,['customer_id'->customer_id]),true;?>">VIEW ADDRESS</a>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
</body>
</html>