<?php 
	$payment = $this->getPayment()['payment']; 
?>

<form action="<?php echo $this->getUrl('save'); ?>" method="post">
	<br/>
	<table class="add-header">
		<tr align="center">
			<td><h2>PAYMENT METHOD INFORMATION</h2></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="add-data-table" align="center">
		<tr>
			<td>Name</td>
			<td><input type="text" name="payment[name]" value="<?php echo $payment->name; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="payment[status]">
					<?php foreach ($payment->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $payment->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2"><button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
			<button type="submit">Submit</button></td>
		</tr>
	</table>
</form>
</body>
</html>