<?php 
$eavAttribute = $this->getEavAttribute()['eavAttribute'];
$entityTypes = $this->getEntityTypes();
$optionsData = $this->getEavAttributeOption();
?>

    <form action="<?php echo $this->getUrl('save')?>" method="post">
        <table class="table table-success table-striped" border="1px">
            <tr align="center">
                <td>Entity Type</td>
                <td><select  name="attribute[entity_type_id]">
                    <?php foreach ($entityTypes as $entityType): ?>
                    <option value="<?php echo $entityType->entity_type_id ?>"><?php echo $entityType->name; ?></option>
                    <?php endforeach; ?>
                </select></td>
            </tr>
            <tr align="center">
                <td>Code</td>
                <td><input type="text" name="eavAttribute[code]" value="<?php echo $eavAttribute->code; ?>"></td>
            </tr>
            <tr align="center">
                <td>Name</td>
                <td><input type="text" name="eavAttribute[name]" value="<?php echo $eavAttribute->name; ?>"></td>
            </tr>
            <tr align="center">
                <td>Input Type</td>
                <td>
                    <select  name="EavAttribute[input_type]"  id="inputTypeSelect" onchange="changeInputType(this)" >
                        <option value="textbox">Text Box</option>
                        <option value="textarea">Text Area</option>
                        <option value="select">Select</option>
                        <option value="multiselect">Multi Select</option>
                        <option value="radio">Radio</option>
                        <option value="checkbox">Checkbox</option>
                    </select>
                </td>
            </tr>
            <tr align="center">
                <td>Backend Type</td>
                <td>
                    <select name="eavAttribute[backend_type]">
                        <option value="int">Integer</option>
                        <option value="float">Decimal</option>
                        <option value="varchar">Varchar</option>
                        <option value="datetime">Date & Time</option>
                        <option value="text">Text</option>
                    </select>
                </td>
            </tr>
            <tr align="center">
                <td>Status</td>
                <td> <select name="eavAttribute[status]" >
                        <?php foreach ($eavAttribute->getStatusOptions() as $key => $value) : ?>
                        <?php $selected = ($key == $eavAttribute->getStatus()) ? "selected" : ''; ?>
                    <option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
                    <?php endforeach; ?>
                </select> </td>
            </tr>
            <tr align="center">
                <td>Backend Model</td>
                <td><input type="text" name="eavAttribute[backend_model]" value="<?php echo $eavAttribute->backend_model; ?>"></td>
            </tr>
            <tr align="center">
                <td colspan="2">
                    <button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
                    <input type="submit" name="submit" value="Save"></td>
            </tr>
        </table>

        <div  id="inputTypeOptionBlock">
            <table class="table table-success table-striped">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th><input type="button" name="add" value="ADD" id="addOption"></th>
                    </tr>
                </thead>
                <tbody id="inputTypeOptionTable">
                    <?php if ($optionsData) : ?>
                    <?php foreach ($optionsData->getData() as $optionData): ?>
                        <tr align="center">
                            <td><input type="text" name="options[exist][<?php echo $optionData->option_id; ?>]" value="<?php echo $optionData->name ?>"></td>
                            <td><input type="button" name="remove" value="REMOVE" class="removeOption" ></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </form>
    <table style="display: none;">
        <tbody id="inputTypeOptionDefault">
            <tr>
                <td>
                    <input type="text" name="options[new][name][]">
                </td>
                <td>
                    <input type="button" name="remove" value="Remove" class="removeOption">
                </td>
            </tr>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(".removeOption").click(function(){
        console.log($(this).parent().parent().remove());
    });

    $("#addOption").click(function(){
        $('#inputTypeOptionTable').prepend($("#inputTypeOptionDefault").html());
    });

    $("#inputTypeSelect").change(function (){
        var inputType = $(this);
        if (inputType.val() == 'select' || inputType.val() == 'multiselect' || inputType.val() == 'radio' || inputType.val() == 'checkbox') {
            $('#inputTypeOptionDiv').show();
        }   
        else {
            $('#inputTypeOptionDiv').hide();
        }
    });

    $(document).ready(function (){
        $("#inputTypeSelect").trigger('change');
    });
</script>