<?php
$attributes = $this->attributes;
?>

	<br/>
	<br/>
	<table class="manage-table" border="1px">
		<tr align="center">
			<td width="70%">MANAGE ATRIBUTES</td>
			<td><button><a href="<?php echo $this->getUrl('add', null , [], true);?>" style="text-decoration: none;">ADD ATTRIBUTE</a></button></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="grid-table" border="1px">
		
		<tr align="center">
			<th>Attribute Id</th>
			<th>Entity_type_id</th>
			<th>Code</th>
			<th>Backend Type</th>
			<th>Name</th>
			<th>Status</th>
			<th>Backend Model</th>
			<th>Input Type</th>
		</tr>
		<?php foreach ($attributes as $attributes): ?>
		<tr align="center">
			<td><?php echo $attributes->attribute_id; ?></td>
			<td><?php echo $attributes->entity_type_id; ?></td>
			<td><?php echo $attributes->code; ?></td>
			<td><?php echo $attributes->backend_type; ?></td>
			<td><?php echo $attributes->name; ?></td>
			<td><?php echo $attributes->getStatusText(); ?></td>
			<td><?php echo $attributes->backend_model; ?></td>
			<td><?php echo $attributes->input_type; ?></td>
		</tr>
		<?php endforeach; ?>
	</table>
</body>
</html>