<?php $category = $this->category; ?>

	<br/>
	<br/>
	<table class="add-data-table" align="center">
		<tr>
			<td>Path</td>
			<td><input type="text" name="category[path]" value="<?php echo $category->path; ?>"></td>
		</tr>
		<tr>
			<td>Name</td>
			<td><input type="text" name="category[name]" value="<?php echo $category->name; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="category[status]">
					<?php foreach ($category->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $category->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2"><button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
			<button type="submit">Submit</button></td>
		</tr>
	</table>
</form>
</body>
</html>