<?php $salesman = $this->getSalesman()['salesman']; ?>
<!DOCTYPE html>
<html>
<head>
	<title>salesman</title>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
<form action="<?php echo $this->getUrl('save'); ?>" method="post">
	<br/>
	<table class="add-header">
		<tr align="center">
			<td><h2>SALESMAN INFORMATION</h2></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="add-data-table" align="center">
		<tr>
			<td>First Name</td>
			<td><input type="text" name="salesman[first_name]" value="<?php echo $salesman->first_name; ?>"></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><input type="text" name="salesman[last_name]" value="<?php echo $salesman->last_name; ?>"></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="salesman[email]" value="<?php echo $salesman->email; ?>"></td>
		</tr>
		<tr>
			<td>Gender</td>
			<td>
				<select name="salesman[gender]">
					<?php foreach ($salesman->getGenderOptions() as $key => $value) : ?>
					<?php $selected = ($key == $salesman->getGender()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Mobile</td>
			<td><input type="text" name="salesman[mobile]" value="<?php echo $salesman->mobile; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="salesman[status]">
					<?php foreach ($salesman->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $salesman->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Company</td>
			<td><input type="text" name="salesman[company]" value="<?php echo $salesman->company; ?>"></td>
		</tr>
		<tr>
			<td colspan="2"><button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
			<button type="submit">Submit</button></td>
		</tr>
	</table>
</form>
</body>
</html>